# Generated by Django 4.1 on 2022-08-20 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rpCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_first_name', models.CharField(max_length=30)),
                ('character_last_name', models.CharField(max_length=45)),
                ('character_played_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_clip_URL', models.CharField(max_length=100)),
                ('date_of_appearance', models.DateTimeField(verbose_name='date and time that the character showed up')),
                ('clip_Streamer', models.CharField(max_length=50)),
                ('character_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastSeenRP.rpcharacter')),
            ],
        ),
    ]
