# Generated by Django 4.1 on 2022-08-27 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lastSeenRP', '0004_alter_appearance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appearance',
            options={'ordering': ('-date_of_appearance',)},
        ),
    ]
