# Generated by Django 4.1 on 2022-09-29 02:56

import datetime
from django.db import migrations, models
import lastSeenRP.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lastSeenRP', '0034_alter_appearance_publish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 22, 56, 2, 351527, tzinfo=datetime.timezone.utc), verbose_name='date and time a user submitted this post'),
        ),
        migrations.AlterField(
            model_name='rpcharacter',
            name='streamers_URL',
            field=models.URLField(blank=True, max_length=60, validators=[lastSeenRP.validators.validate_streamer_url]),
        ),
    ]
