# Generated by Django 4.1 on 2022-09-29 04:00

import datetime
from django.db import migrations, models
import lastSeenRP.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lastSeenRP', '0037_alter_appearance_publish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 0, 0, 29, 722347, tzinfo=datetime.timezone.utc), verbose_name='date and time a user submitted this post'),
        ),
        migrations.AlterField(
            model_name='rpcharacter',
            name='character_first_name',
            field=models.CharField(max_length=30, validators=[lastSeenRP.validators.validate_character_first_name]),
        ),
        migrations.AlterField(
            model_name='rpcharacter',
            name='character_nick_name',
            field=models.CharField(blank=True, default='', max_length=50, validators=[lastSeenRP.validators.validate_character_nick_name]),
        ),
    ]
