# Generated by Django 4.1 on 2022-10-01 01:36

import datetime
from django.db import migrations, models
import lastSeenRP.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lastSeenRP', '0044_appearance_submittedby_alter_appearance_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='date_of_appearance',
            field=models.DateTimeField(validators=[lastSeenRP.validators.validate_appearance_time], verbose_name='date and time that the character showed up'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 21, 36, 18, 94908, tzinfo=datetime.timezone.utc), verbose_name='date and time a user submitted this post'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='twitch_clip_URL',
            field=models.URLField(max_length=100, validators=[lastSeenRP.validators.validate_clip_url]),
        ),
    ]
