# Generated by Django 4.1 on 2022-08-27 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastSeenRP', '0003_alter_appearance_publish_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appearance',
            options={'ordering': ('-publish_time',)},
        ),
        migrations.AlterField(
            model_name='appearance',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date and time a user submitted this post'),
        ),
    ]
