# Generated by Django 4.1 on 2022-09-21 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastSeenRP', '0005_alter_appearance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 20, 26, 13, 223370), verbose_name='date and time a user submitted this post'),
        ),
    ]
