# Generated by Django 4.1 on 2022-09-25 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastSeenRP', '0019_alter_appearance_publish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 16, 11, 19, 812995, tzinfo=datetime.timezone.utc), verbose_name='date and time a user submitted this post'),
        ),
        migrations.AlterField(
            model_name='rpcharacter',
            name='character_nick_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rpcharacter',
            name='character_played_by',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='rpcharacter',
            name='streamers_URL',
            field=models.CharField(blank=True, default='Unknown', max_length=60),
        ),
    ]
