# Generated by Django 4.1 on 2022-09-28 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastSeenRP', '0023_alter_appearance_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 0, 18, 19, 51091, tzinfo=datetime.timezone.utc), verbose_name='date and time a user submitted this post'),
        ),
        migrations.AlterField(
            model_name='rpcharacter',
            name='character_image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rpcharacter',
            name='character_played_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rpcharacter',
            name='streamers_URL',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
