# Generated by Django 4.1 on 2022-09-28 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastSeenRP', '0027_alter_appearance_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 1, 17, 42, 55399, tzinfo=datetime.timezone.utc), verbose_name='date and time a user submitted this post'),
        ),
    ]
