# Generated by Django 4.1 on 2022-09-29 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastSeenRP', '0033_alter_appearance_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 21, 17, 49, 497510, tzinfo=datetime.timezone.utc), verbose_name='date and time a user submitted this post'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='twitch_clip_URL',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rpcharacter',
            name='streamers_URL',
            field=models.URLField(blank=True, max_length=60),
        ),
    ]
