# Generated by Django 4.1 on 2022-10-01 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastSeenRP', '0043_alter_appearance_publish_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='submittedBy',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 21, 10, 26, 703608, tzinfo=datetime.timezone.utc), verbose_name='date and time a user submitted this post'),
        ),
    ]
