# Generated by Django 4.1.1 on 2022-10-04 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastSeenRP', '0045_alter_appearance_date_of_appearance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='date_of_appearance',
            field=models.DateTimeField(verbose_name='date and time that the character showed up'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 20, 49, 3, 842663, tzinfo=datetime.timezone.utc), verbose_name='date and time a user submitted this post'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='submittedBy',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='twitch_clip_URL',
            field=models.URLField(max_length=100),
        ),
    ]
