# Generated by Django 4.1.1 on 2022-10-16 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastSeenRP', '0047_alter_appearance_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 2, 57, 54, 643265, tzinfo=datetime.timezone.utc), verbose_name='date and time a user submitted this post'),
        ),
    ]
