# Generated by Django 4.1.1 on 2022-10-16 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lastSeenRP', '0048_alter_appearance_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time a user submitted this post'),
        ),
    ]
